version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_dev
    restart: unless-stopped

    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: clickbeard_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend_user -d clickbeard_db"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net: